name = input("name:")
vazn = input("vazn (KG):")
vazn_float = float (vazn)
ghad = input("ghad (M):")
ghad_float = float(ghad)
BMI = vazn_float/(ghad_float**2)
print(name,"aziz","bmi shoma:",BMI)
