# -*- coding: utf-8 -*-
"""python_with_soroush.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FJo1l4VsEYjaHfbaZybEHN7NPUzQxqDV
"""

first_name = "farzin"
last_name = "ahmadi"
win_ver = 10
build_num = 12345.43343
x,y,z = 34,4.5,1.234
x,y,z

full_name = first_name + ' '+ last_name
full_name

message = 'first_name is using windows win_ver Build: as_build'
message

message1 = f'{first_name} is using windows {win_ver} Build: as_build'
message1

input_name = input("enter your name")
print(f'Hello {input_name}')

str(555)

int(23.4)

float(5)

number_of_pet =int(input("how many pets do you have ?"))
print(f'I guess you have {number_of_pet//2} dog')

p_cat = 0.5
p_dog = 0.5
print(p_cat > p_dog)

if p_cat > p_dog :
  print("it is a cat ")
elif p_cat < p_dog :
  print("it is a dog")
else : 
  print("I can cot decide")

while True:
 input_str = input("Enter p_cat")

 if input_str == "exit":
   break
 p_cat = float(input_str)
 if (p_cat < 0) or (p_cat > 1):
   print('p_cat must be between 0 and 1')
   continue
 p_dog = 1 - p_cat
 if p_cat > p_dog :
  print("it is a cat ")
 elif p_cat < p_dog :
  print("it is a dog")
 else : 
  print("I can cot decide")

for i in range(1,11):
  print(i)

for i in range(1,11,2):
  print(i)

for i in range(6,-5,-1):
  print(i)

for _ in range(2):
  i = 5
  print(5)
  print("I love my self")

# making function 

def print_hello():
  print("Hello")

print_hello()

def print_hello(name):
  print(f"Hello {name}")

print_hello("Farzin")

def prob_to_name (p_cat):
  if p_cat > 0.5 :
    prediction = 'cat'
  elif p_cat < 0.5 :
    prediction = 'dog'
  else:
    prediction = "unknown"
  print(prediction)

prob_to_name(0.8)

def prob_to_name (p_cat,owner):
  if p_cat > 0.5 :
    prediction = 'cat'
  elif p_cat < 0.5 :
    prediction = 'dog'
  else:
    prediction = "unknown"

  print(f"{owner} has a {prediction}")

prob_to_name(0.8,"farzin")

def prob_to_name (p_cat,owner="Farzin"):
  if p_cat > 0.5 :
    prediction = 'cat'
  elif p_cat < 0.5 :
    prediction = 'dog'
  else:
    prediction = "unknown"

  print(f"{owner} has a {prediction}")

prob_to_name(0.8,)

def prob_to_name (p_cat,breed,owner="farzin",pet_age = 3):
  if p_cat > 0.5 :
    prediction = 'cat'
  elif p_cat < 0.5 :
    prediction = 'dog'
  else:
    prediction = "unknown"

  print(f"{owner} has a {breed} {prediction} who is {pet_age} years old!")

prob_to_name(0.9,"persion")

def prob_to_name (p_cat,breed,owner=None,pet_age = 3):
  if p_cat > 0.5 :
    prediction = 'cat'
  elif p_cat < 0.5 :
    prediction = 'dog'
  else:
    prediction = "unknown"

  print(f"{owner} has a {breed} {prediction} who is {pet_age} years old!")

prob_to_name(0.9,"persion")

# with output

def prob_to_name (p_cat,breed,owner=None,pet_age =None):
  if p_cat > 0.5 :
    prediction = 'cat'
  elif p_cat < 0.5 :
    prediction = 'dog'
  else:
    prediction = "unknown"
  if owner is not None:

    print(f"{owner} has a {breed} {prediction} who is {pet_age} years old!")
  else :
      print(f"This {breed} is {prediction}  {pet_age} years old!")


  return prediction
prob_to_name(0.9,"persion",pet_age=5)

